
package org.testplayground.consumer;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EmployeeDao", targetNamespace = "http://interfaces.dao.playground.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeDao {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteEmployeeById", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.DeleteEmployeeById")
    @ResponseWrapper(localName = "deleteEmployeeByIdResponse", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.DeleteEmployeeByIdResponse")
    @Action(input = "http://interfaces.dao.playground.org/EmployeeDao/deleteEmployeeByIdRequest", output = "http://interfaces.dao.playground.org/EmployeeDao/deleteEmployeeByIdResponse")
    public void deleteEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.testplayground.consumer.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.UpdateEmployeeResponse")
    @Action(input = "http://interfaces.dao.playground.org/EmployeeDao/updateEmployeeRequest", output = "http://interfaces.dao.playground.org/EmployeeDao/updateEmployeeResponse")
    public Employee updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.testplayground.consumer.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveEmployee", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.SaveEmployee")
    @ResponseWrapper(localName = "saveEmployeeResponse", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.SaveEmployeeResponse")
    @Action(input = "http://interfaces.dao.playground.org/EmployeeDao/saveEmployeeRequest", output = "http://interfaces.dao.playground.org/EmployeeDao/saveEmployeeResponse")
    public Employee saveEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.testplayground.consumer.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://interfaces.dao.playground.org/", className = "org.testplayground.consumer.GetEmployeeByIdResponse")
    @Action(input = "http://interfaces.dao.playground.org/EmployeeDao/getEmployeeByIdRequest", output = "http://interfaces.dao.playground.org/EmployeeDao/getEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
