


management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      show-details: always


info:
  app:
    name: 'My App'
    test: '@info.testPom@'


server:
  port: 8955
